[options]
addons_path = addons,odoo/addons
admin_passwd = admin
db_host = False
db_port = False
db_user = odoo_user
db_password = abd123
db_name = ql_taisan
dbfilter = ^ql_taisan$
logfile = odoo.log
xmlrpc_port = 8069
